import {writeFile} from 'node:fs/promises';
import {adaptMatch} from './statsbomb-adapter.mjs';
const revision='4b73468fc5b0f1950f9f66fada70ad3a4f9327cb';
const base=`https://raw.githubusercontent.com/hudl/open-data/${revision}`;
async function get(path){const r=await fetch(`${base}/${path}`);if(!r.ok)throw Error(`Download failed: ${r.status}`);return r.json();}
const [matches,events]=await Promise.all([get('data/matches/43/106.json'),get('data/events/3869685.json')]);
const match=matches.find(m=>m.match_id===3869685);if(!match)throw Error('Match not found');
const data=adaptMatch(events,match);
data.source={name:'StatsBomb Open Data',url:'https://github.com/hudl/open-data',revision,eventUrl:`${base}/data/events/3869685.json`,retrievedAt:new Date().toISOString()};
await writeFile(new URL('../dist/match-data.js',import.meta.url),`// Generated by npm run data:refresh.
export const matchData = ${JSON.stringify(data,null,2)};
`);
console.log(`Saved ${data.shots.length} real shots: ${data.teams.join(' vs ')}`);
